@startuml MyUML
scale 2

class Point {
  - x: int
  - y: int
  + Point(x:int, y:int)
  + getX():int
  + setX(x: int):void
  + getY():int
  + setY(y: int):void
}

class Circle {
  - point:Point
  - radius: int
  + setPoint(Point)
  + getPoint():Point
  + setRadius(int)
  + getRadius():int
  + toString():String
}


Point <|-- Circle
@enduml
