// 추가

package kr.gilju.preparedstatement_ex;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

import kr.gilju.helpers.DBHelper;

public class App01 {
  public static void main(String[] args) {
    /** 1) 저장할 데이터와 입력받기 */
    Scanner scanner = new Scanner(System.in);

    System.out.print("학과명: ");
    String dname = scanner.nextLine();

    System.out.print("위치: ");
    String loc = scanner.nextLine();

    scanner.close();

    /** 2) sql구문 정의하기 */
    // department 테이블에 컴퓨터정보과를 추가하기 위한 sql의 템플리
    // department 컬럼은 auto_incrment 이므로 insert에서 명시하지 않아도 된다
    String sql = "INSERT INTO department (dname, loc) VALUES (?, ?)";

    /** 3) dbhelper 를 통한 db접속처리 */
    Connection conn = DBHelper.getInstance().open();

    /** 4) sql 구문 실행하기 */
    // sql 문의 템플릿을 사용하여 쿼리 실행을 준비하는 객체
    PreparedStatement pstmt = null;

    // 처리결과를 받을객체
    ResultSet rs = null;

    // 결과값(저장된 데이터의 수)
    int result = 0;

    // 결과값 (생성된 auto_increment 값)
    int autoGeneratedID = 0;

    try {
      // pstmt 객체할당 --> auto_incrment 조회 옵션 사용함
      pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

      // sql문의 ? 자리에 데이터를 바인딩
      pstmt.setString(1, dname);
      pstmt.setString(2, loc);

      // sql문 실행하기 -> 결과 행 리턴됨 (주의! 파라미터 없음)
      result = pstmt.executeUpdate();

      // 생성된 auto_increment 값 얻기
      rs = pstmt.getGeneratedKeys();
      rs.next();
      autoGeneratedID = rs.getInt(1);
    } catch (SQLException e) {
      e.printStackTrace();
    } finally {
      // sql을 수항해는 과정에서 생성한 객체는 반드시 생성 역순으로 닫아야함
      if (rs != null) {
        try {
          rs.close();
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
      if (pstmt != null) {
        // 객체닫기
        try {
          pstmt.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
    }

    /** 5) 결과출력 */
    System.out.println(result + " Record Insert");
    System.out.println("New Deptno=" + autoGeneratedID);

    /** 6) db 접속해제 */
    DBHelper.getInstance().close();
  }
}